# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bons/debian-jessie64"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  config.vm.synced_folder ".", "/vagrant", disabled: true

  #OBLIGATORIO - Path del directorio en el host a montar en la virtual
  #Puede ser absoluto o relativo
  config.unificar.local_dir = "."

  #OBLIGATORIO - Path absoluto del punto de montaje en la virtual
  config.unificar.remote_mountpoint = "/vagrant"

  #config.unificar.debug = true

end
